name = "stracohouse-frontend"
main = ".output/server/index.mjs"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "stracohouse.be", custom_domain = true }
]

[assets]
directory = ".output/public"
